### ISSUE TITLE
API for accessing Ledger data from another plugin

### ISSUE THREAD

**Issue by AuroraLS3** [QuiltServerTools/Ledger#110]
### Is your feature request related to a problem?

Hello, I got a feature request on my analytics plugin to add support for Ledger data.

To me Ledger appears to be an event logging tool so there's vast data available. I think following data points would be interesting for users to see:

- How many ores the player has mined comparing to regular stone
- Any xray warning information? (I'm unsure if this is available, but the ticket I got mentioned it)
- Anything else you would like the users to see on a dashboard about a player. Lists of ~500 are manageable and any metadata (Like aggregates of different kinds of events of a player) may be interesting as well - Server wide aggregates may also be interesting if you want to implement an api for getting them, but it might be out of scope for this ticket.

### Describe the solution you'd like.

- I would like to get a memory optimized view of this data (Like block counts) to avoid crashing server when getting the data (A thing that happened with CoreProtect API).
  - I get a Player UUID and that is all I have so if you need other stuff like world information to make a query a separate api endpoint for listing those would be appericiated.
  - [The Logblock API is a good example](https://github.com/LogBlock/LogBlock/wiki/API) ([Their separate api method for block counts](https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/LogBlock/LogBlock.java#L340))
- Some way of getting list of ores and list of different kinds of stone in order to query their counts more effectively (Since modded can have more types of ore than what I can manually code in)
  - I'm planning on visualizing this on a table "Ore name - count - ratio / stone"
  - I might need the name of the ore
  - If possible the rarity of the ore may be useful for determining which ratios to show more prominently, but it may be out of scope for this ticket.
- Some way to get a list of xray warnings for a player if you store that data somewhere

### Describe alternatives you've considered.

I tried to look at the code for existing APIs that could do this, but my kotlin is kinda poor and I was unable to find methods to do this using IntelliJ code completion in a Java project

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

- The feature request I got https://github.com/plan-player-analytics/Plan/issues/2094

**Comment by PotatoPresident** [comment]
A more friendly, java usable API is something I've had in the back of my mind for a while. I'll see what I can do. As for reporting what ores and stone have been added to the game, that seems out of scope for Ledger.

**Comment by PotatoPresident** [comment]
Still planning to do an API, but I just had a thought. Everything you requested can be done in vanilla. Block counts are all logged by the vanilla statistics system. You can also get all the ores from the `#ores` block tag.

**Comment by AuroraLS3** [comment]
Alright - I'll consider that. :)
I don't really know what the user is after since they ignored my issue template so I had to wing this request :S
