### ISSUE TITLE
Incompatible with Cardboard

### ISSUE THREAD

**Issue by Dreeam-qwq** [QuiltServerTools/Ledger#113]
### Expected behavior

can't launch server with ledger and Cardboard

### Observed/actual behavior

can't launch server with ledger and Cardboard

### Steps/models to reproduce

1. add ledger and Cardboard #42
2. launch the server
3. see the error

### What operating system are you running

Windows

### Minecraft version

1.17.1

### Ledger version

1.1.1+build.362

### Logs

https://paste.gg/p/anonymous/2ae8aa4fe09c4e46aac1261326f6a290

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by vacla** [comment]
This is no bug, you can read here why Ledger is not compatible with Cardboard: https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf
