### ISSUE TITLE
Things that aren't logged by ledger

### ISSUE THREAD

**Issue by redstonerti** [QuiltServerTools/Ledger#12]
Good job on fixing the errors and making the commands easier to use!
But it's not really useful for preventing griefing yet because:

- [x] When a player sets off a tnt, it doesn't count as them doing it
- [x] Item frames aren't tracked at all
- [x] Signs don't retain the text written on them
- [x] When you replace water or lava with another block it just rollbacks to air
- [x] Chest's contents lost on break
- [x] Farmland trampling
- [x] Sponges clearing out water aren't tracked
- [ ] When a player flint and steels a tree and you rollback, it fills back whatever blocks were broken but the fire remains. Also, it doesn't count as that player doing it. Generally, rolling back fire doesn't work well
- [x] When a player activates an end crystal it doesn't count as that player doing it
- [x] Dispenser block placement (and other things)
- [x] Path flattening
- [ ] Piston movement
- [x] Removing or adding books to a lectern
- [x] The state of levers
- [ ] Moss transmutation
- [x] Now it shows that a explosion broke something but I would love to see what the explosion was (a bed, respawn anchor, etc) and then also who set it on.
- [x] Ledger doesn't log when you click with a shovel on a campfire or when you light it
- [x] Ledger doesn't log bamboo getting broken by gravity
- [x] Ledger doesn't log it if you light candles
- [x] When you bonemeal Rooted Dirt the newly grown roots doesn't get logged
- [x] Leaf decay isn't logged
- [x] The snow that snowgolems place isn't logged
- [x] Flowerpot transactions aren't logged
- [x] Scaffholding/supported blocks
- [x] Frost water logging
- [ ] Bed rotation is not logged so only one half of the bed will get restored facing the wrong way. 
- [ ] Fences do not keep their connection with other fences, same with double chests
- [x] Fire placed by explosions not logged
- [x] Armor stand deaths not logged
- [ ] Cauldron transactions
- [x] Ravagers breaking leaves
- [ ] Jukebox transactions
- [x] Players changing day/night state of daylight sensors
- [x] Player changing the notes on a noteblock
- [ ] I think shooting/breaking Chorus Flower with a bow & arrow is not logged
- [x] growing kelp, weeping vines, twisting vines, grass, fern & seagrass with bonemeal
- [x] Putting wax on any copper block, the same for removing wax of any copper block
- [x] Coral & coral fans dying
- [ ] Paintings placement/removal
- [x] The creation of nether portals
- [ ] #123

**Comment by PotatoPresident** [comment]
I think signs should actually retain text... I'll have to check though

**Comment by SnaveSutit** [comment]
Moss Transmutation is also untracked. It's a new 1.17 feature.
Right clicking on the moss block with bonemeal will transmutate any nearby/connected stone blocks into moss.

**Comment by PotatoPresident** [comment]
> 
> 
> Moss Transmutation is also untracked. It's a new 1.17 feature.
> Right clicking on the moss block with bonemeal will transmutate any nearby/connected stone blocks into moss.

Just add it to the list

**Comment by redstonerti** [comment]
> I think signs should actually retain text... I'll have to check though
No they don't, i checked before writing these :)

**Comment by PotatoPresident** [comment]
> No they don't, i checked before writing these :)

That's annoying, I've fixed it twice

> Btw i added a few more things that i ran into, i hope i'm not overwhelming you with all these tasks
Not at all, I've told yitzy I want to log **everything**, we are just more focused on getting everything working smoothly for the time being.

**Comment by emielderckx** [comment]
Maybe im wrong with some of these. Also this is not meant as some sort of push to work harder but just helping finding the missing pieces <3

- [ ] Now it shows that a explosion broke something but I would love to see what the explosion was (a bed, respawn anchor, etc) and then also who set it on.

- [ ] Ledger doesn't log when you click with a shovel on a campfire or when you light it

- [ ] Ledger doesn't log it if you light candles

- [ ] Ledger doesn't log bamboo getting broken by gravity

- [ ] When you bonemeal Rooted Dirt the newly grown roots doesn't get logged

- [ ] Leaf decay isn't logged

- [ ] The snow that snowgolems place isn't logged

- [ ] Flowerpot transactions aren't logged

- [ ] Scaffholding that gets broken by gravity doesn't get logged

**Comment by PotatoPresident** [comment]
If anyone has more things that aren't logged and on the list please do add a comment here or discord

**Comment by yitzy299** [comment]
> When a player sets off a tnt, it doesn't count as them doing it

This should be logged as a player's action if the player directly explodes it

**Comment by yitzy299** [comment]
All of the explosion related ones are dependent on that new API, so should probably be moved to another issue

**Comment by JumperCzech** [comment]
For explosions from Creepers/Ghasts, it would be nice if it was logged who they were aggroed to. In case someone tries to avoid logging by bringing a creeper to someone's house.

**Comment by LambdAurora** [comment]
To add: 
 - [ ] Frost Walker logging

**Comment by Altirix** [comment]
a few others, 

- [ ] Bed rotation is not logged so only one half of the bed will get restored facing the wrong way. 
- [ ] Fences do not keep their connection with other fences
- [ ] OptimizeTNT from carpet prevents logging of explosions

**Comment by yitzy299** [comment]
I've been working a bit on this issue in the `more-logging` branch, I'll tick things off as I do them

**Comment by emielderckx** [comment]
Maybe add:
- [ ] Log changes made via WorldEdit
- [ ] Log username changes
- [ ] Log player deaths
- [ ] Log player sessions (logins/logouts)
- [ ] Log chat messages and commands used by players.
- [ ] The creation of nether portals

**Comment by yitzy299** [comment]
> Maybe add:
> 
> * [ ]  Log changes made via WorldEdit
> * [ ]  Log username changes
> * [ ]  Log player deaths
> * [ ]  Log player sessions (logins/logouts)
> * [ ]  Log chat messages and commands used by players.
> * [ ]  The creation of nether portals

There's already a large amount of player data which ledger already logs, but can be exposed to the user with a command, so I've added everything else to the main list

**Comment by JumperCzech** [comment]
Transactions to/from Hopper/Chest Minecarts

**Comment by emielderckx** [comment]
New things:
- [ ] Ledger doesn't log sugarcane, cactus getting broken by gravity
- [ ] Wet sponge placed in the nether gets logged as player placing normal sponge
- [ ] Bonemealing saplings/growth of trees is not logged
- [ ] When you bonemeal grass to tall grass
- [ ] When you bonemeal a grass block the placed grass/flowers are not logged
- [ ] Soul sand and heads getting transformed into a wither
