### ISSUE TITLE
Armor stand interactions are not logged

### ISSUE THREAD

**Issue by BelkovV** [QuiltServerTools/Ledger#129]
### Expected behavior

After taking armor from an armor stand, this will be noted as a player action and as so, will appear in the "/ledger search source:player" list.

### Observed/actual behavior

Nothing seems to be logged at all

### Steps/models to reproduce

Here's a quick video showcasing the process:
https://user-images.githubusercontent.com/71695040/145356866-4b406c07-bc6f-4423-bae1-ee9c82dd6f36.mp4

(i'm using carpet and lithium as you can see from my latest log. May be a compatibility issue)

### What operating system are you running

Linux

### Minecraft version

1.18 Server

### Ledger version

1.2.0

### Logs

https://github.com/QuiltServerTools/Ledger/files/7683304/latest.log

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

I'm using carpet and lithium as you can see from my latest log. So this may be a compatibility issue

**Comment by Altirix** [comment]
https://github.com/QuiltServerTools/Ledger/pull/119
