### ISSUE TITLE
Ledger interfering with other mod's sql databases

### ISSUE THREAD

**Issue by SnaveSutit** [QuiltServerTools/Ledger#13]
How to reproduce:
- setup a server with these mods:
  - ledger 1.0.0
  - gunpowder-base 1.0.0 1.17-rc2
  - gunpowder-teleport 1.0.7 1.17-rc2
- try to use the `/warp` command
- The game will crash, and spit out this crash log: [crash-2021-06-09_15.02.31-server.txt](https://github.com/QuiltServerTools/Ledger/files/6624866/crash-2021-06-09_15.02.31-server.txt)

Server log for extra info: [latest.log](https://github.com/QuiltServerTools/Ledger/files/6624867/latest.log)

Removing ledger from the server solves the issue.

**Comment by martmists-gh** [comment]
Possible solution:

Check for gunpowder-base to be present
If present, use Gunpowder's database API
Else, use own database.

**Comment by yitzy299** [comment]
Will fix this relatively soon by shadowing our database, but other mods should do this as well

**Comment by yitzy299** [comment]
This commit does not fix the compat, but it fixes the issue from our end. Other mods should not be using `include` for sqlite or exposed.
