### ISSUE TITLE
Please confirm support for 1.18.1

### ISSUE THREAD

**Issue by wolfen351** [QuiltServerTools/Ledger#130]
### Is your feature request related to a problem?

I would like to upgrade my world to 1.18.1, but this mod is vital, so I'd like to know if it will work?

### Describe the solution you'd like.

A simple confirmation that it will work on 1.18.1 

### Describe alternatives you've considered.

I could test it myself, and probably will in the next week.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by PotatoPresident** [comment]
Yes

**Comment by wolfen351** [comment]
Awesome, thanks!
