### ISSUE TITLE
Broken Anvil does not show up in logs

### ISSUE THREAD

**Issue by dhalucario** [QuiltServerTools/Ledger#132]
### Expected behavior

When I use /lg inspect and check a block location it isn't showing who broke the anvil in the logs.

### Observed/actual behavior

The logs did not contain any reports about who last used the anvil to break it.

### Steps/models to reproduce

1. Place down anvil
2. Use anvil until broken
3. Check logs using /lg inspect to find that there is no anvil logged.

### What operating system are you running

Linux

### Minecraft version

1.18.1

### Ledger version

1.2.0

### Logs

Don't have any.

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by dhalucario** [comment]
Oh, I didn't see #12 because its closed. Sorry.

**Comment by Altirix** [comment]
also https://github.com/QuiltServerTools/Ledger/pull/127 will still need to be finished up, get reviewed and finally merged. but feel free to test it in a dev environment.

**Comment by dhalucario** [comment]
I tried to merge it into master but I can't seem to get it compiled. I wanted to test on 1.18.1 since I use that for my server. Sadly it seems like that will take a bit more work. At least with openjdk 17 I can't seem to get it compiled on Fedora.

**Comment by Tom-The-Geek** [comment]
I've approved actions to run for that PR so there's now prebuilt artifacts available for it [here](https://github.com/QuiltServerTools/Ledger/actions/runs/1570453996) if you're struggling to get it to build

**Comment by dhalucario** [comment]
![image](https://user-images.githubusercontent.com/10533763/146980460-1d9e274d-2f56-433f-8184-6fc0afd47385.png)
LGMT
