### ISSUE TITLE
Chunk loading extremely slow

### ISSUE THREAD

**Issue by RandomGgames** [QuiltServerTools/Ledger#140]
### Expected behavior

The mod has almost no performance impact on generating new chunks

### Observed/actual behavior

Server gets extremely bogged down when run on a hard drive, causing chunks to generate very slowly. Disk write speeds fluctuated around ~<1.3 MB/s when mod is installed, and when not installed jumps to >3.5 MB/s.

### Steps/models to reproduce

1. Run a fabric 1.18.1 server on a hard disk drive with the mod
2. Notice very slow chunk generation (I've tested with 4 and 6GB of ram)
3. Take mod away
4. Notice significant chunk loading improvement.

### What operating system are you running

Windows

### Minecraft version

1.18.1

### Ledger version

1.2.0

### Logs

https://pastebin.com/rAJz4gs9

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by yitzy299** [comment]
Switch your database to MySQL hosted on another machine, hard drives are not fast enough for an sqlite database of the throughput that ledger provides
