### ISSUE TITLE
Show items being removed or placed on both sides of large chests

### ISSUE THREAD

**Issue by arnokeesman** [QuiltServerTools/Ledger#144]
### Is your feature request related to a problem?

large chests don't show any item interactions when inspecting the right side

### Describe the solution you'd like.

Show item interactions when inspecting either side of a large chest

### Describe alternatives you've considered.

Just clicking the left side ,but can be confusing when the right side doesn't show anything, and depending on orientation of the chest the left side can be hidden quite far in a wall which makes it close to if not impossible to inspect by clicking instead of search

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by yitzy299** [comment]
Implemented in 5fd57b5
