### ISSUE TITLE
When sponge are placed in the sea, the server crashes

### ISSUE THREAD

**Issue by Soochaehwa** [QuiltServerTools/Ledger#148]
### Expected behavior

Use sponge

### Observed/actual behavior

Server crash

### Steps/models to reproduce

1. Place a sponge in the sea
2. Server crash

### What operating system are you running

Windows

### Minecraft version

1.18.1

### Ledger version

1.2.1

### Logs

https://gist.github.com/Soochaehwa/cdbf5a97d691415a4d0e88f703ae74bd

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
Fixed, download dev build [here](https://github.com/QuiltServerTools/Ledger/actions/runs/1816488274)

New release soon
