### ISSUE TITLE
[Permissions] Unable to set specific permissions

### ISSUE THREAD

**Issue by KJP12** [QuiltServerTools/Ledger#165]
### Expected behavior

`/luckperms user _KJP12 permissions set ledger.commands.inspect true` to allow for usage of `/lg i` and `/ledger inspect`

### Observed/actual behavior

The permission isn't set as expected, requiring one to enable `ledger.commands`, which just allows the entire block under Luckperms, which is *not* what we want.

### Steps/models to reproduce

1. Be not op but have some level ability to set permissions
   - Alternatively, have an alt ready, or use the console to set permissions.
2. Set `ledger.commands.inspect` or other subcommands to true
   - With Luckperms: `/luckperms user _KJP12 permissions set ledger.commands.inspect true`
3. Attempt to use `/lg i` or `/ledger inspect`

### What operating system are you running

Linux

### Minecraft version

1.18.2

### Ledger version

1.2.4

### Logs

N/A; no applicable logs were emitted from this.

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

<details><summary>/luckperms info</summary>

```md
[LP] Running LuckPerms v5.4.9 by Luck.
[LP] -  Platform: Fabric
[LP] -  Server Brand: fabric@0.48.0+1.18.2
[LP] -  Server Version:
[LP]      1.18.2 - fabric-api@0.4.4+d7c144a860
[LP] -  Storage:
[LP]      Type: H2
[LP]      File Size: 0.07MB
[LP] -  Extensions:
[LP]      None
[LP] -  Messaging: None
[LP] -  Instance:
[LP]      Static contexts: None
[LP]      Online Players: 4 (9 unique)
[LP]      Uptime: 17h 19m 44s
[LP]      Local Data: 4 users, 2 groups, 0 tracks
```
</details>

**Comment by vacla** [comment]
@KJP12 do you also have `ledger.commands.root` as permission?

**Comment by KJP12** [comment]
No, that wasn't set; it does seem that was the cause as setting that to true lets `lg i` work as expected without access to the rest.

Perhaps better discoverability for the root node could be in order?

**Comment by PotatoPresident** [comment]
Yeah I'd like to find a better solution at some point. [It is documented on the wiki though](https://quiltservertools.net/Ledger/v1.2.4/commands/root/).
