### ISSUE TITLE
'Mismatch in destroy block' console spam when using inspect command

### ISSUE THREAD

**Issue by jwosty** [QuiltServerTools/Ledger#166]
### Expected behavior

`/ledger inspect` should allow me to inspect block without console spam resulting.

### Observed/actual behavior

Inspect works as expected, however the console logs lines such as this for every block inspected:

``Server thread/ Mismatch in destroy block pos: class_2338{x=-123, y=86, z=108} class_2338{x=-118, y=86, z=107}``

Happens in survival but not creative mode.

### Steps/models to reproduce

1. Turn on `/ledger inspect`
2. Click on a block in survival mode

### What operating system are you running

Linux

### Minecraft version

1.18.2

### Ledger version

1.2.4

### Logs

https://gist.github.com/jwosty/9bfc5c307736ef5b34be502ec977509e

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
This also just happens with vanilla desync. Would be difficult to fix without any real reason.
