### ISSUE TITLE
Ledger and Charm Chat Conflicts

### ISSUE THREAD

**Issue by WanderingCat27** [QuiltServerTools/Ledger#169]
### Expected behavior

normal chat messages

### Observed/actual behavior

![image](https://user-images.githubusercontent.com/51253586/169374100-f475a813-8d44-4e3d-a824-0672a0956fb2.png)

### Steps/models to reproduce

install charm (charm-fabric-1.18-4.1.0) and ledger together
run a command like /ledger search source:user

### What operating system are you running

Windows

### Minecraft version

1.18.2

### Ledger version

1.2.4

### Logs

idk where ips are logged in logs so I would rather not paste the whole file + its easily replicatable

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

I am not sure which mod the issue resides in so I am going to leave an issue in both mods. Wish I could give more information than this, but this is all I know.

**Comment by PotatoPresident** [comment]
Update [server translations](https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.12%2B1.18.2/server-translations-api-1.4.12%2B1.18.2.jar)
