### ISSUE TITLE
Ledger crashes with null parameter in BlockChangeCallback

### ISSUE THREAD

**Issue by udidifier** [QuiltServerTools/Ledger#174]
### Expected behavior

Expected no random CTD when loading modded chunks

### Observed/actual behavior

Random CTD when loading modded chunks

### Steps/models to reproduce

1. Heavily modded minecraft client
2. Fly around world for awhile
3. Eventual CTD

### What operating system are you running

Windows

### Minecraft version

1.18.2

### Ledger version

1.2.4

### Logs

https://pastebin.com/VmkR1Gdc

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Modlist is included in pastebin, may try to narrow it down but it will be hard.

**Comment by PotatoPresident** [comment]
Was [fixed a while ago](https://github.com/QuiltServerTools/Ledger/pull/170). Grab a more recent build from actions.

**Comment by udidifier** [comment]
Gotcha, my bad. Thanks!!
