### ISSUE TITLE
Ledger failing to run on 1.19

### ISSUE THREAD

**Issue by imsofi** [QuiltServerTools/Ledger#178]
### Expected behavior

Commands work as expected on 1.19.

### Observed/actual behavior

Many commands just dont give any output, or act weirdly with `/ledger i` saying "No results for that search" on changed blocks, otherwise giving no output when right clicking.

### Steps/models to reproduce

1. Install Ledger 1.2.5 to a Fabric 1.19 server.
2. Op yourself.
3. Log in and break and add blocks.
4. See commands such as `/ledger i` fail with "No results for that search" even if `/ledger preview` shows the changed blocks.

### What operating system are you running

Linux

### Minecraft version

1.19

### Ledger version

1.2.5

### Logs

https://paste.pythondiscord.com/xivaluriha

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Both Fabric 1.19 and Quilted 1.19 fail in the exact same fashion.

I have had this mod work previously on a 1.18.2 server, and i fail to see what i may have changed to make it not work on 1.19.

Related: #57 #65

**Comment by imsofi** [comment]
I also attempted to remove the `ledger.sqlite` to generate a new one, but same behavior regardless of new or old db.

**Comment by arnokeesman** [comment]
Just tried on my 1.19 server, it works fine for me.
Tip:
Left click a block - Inspect the block clicked
Right click a block - Inspect the block on the side clicked

**Comment by imsofi** [comment]
Yeah, the same pattern emerges. Left clicking any placed block or changed block gives no output, clicking a known not changed block will give a "No results for that search".

**Comment by PotatoPresident** [comment]
enable sendCommandFeedback gamerule

**Comment by imsofi** [comment]
That is quite an oversight on my end for not realizing that. That did fix the issue. Its likely from a datapack which changed the toggle to disabled that i then later removed. Which is what really stumped me about this issue.

Maybe a nice debugging step to add to the documentation under a `FAQ` or `Installation` page?

**Comment by PotatoPresident** [comment]
Yeah I've seen it a few times. Probably a good idea
