### ISSUE TITLE
Restrictions on teleporting to logs (configurable)

### ISSUE THREAD

**Issue by LuciusofLegend** [QuiltServerTools/Ledger#187]
### Is your feature request related to a problem?

On my server, I want my moderators to be able to investigate suspicious logs, but I don't want them teleporting around.

### Describe the solution you'd like.

My proposed solution is a few more configuration options:

Teleporting to logs puts you into Spectator (configurable to be any gamemode)
You cannot move (true or false)
You cannot look around (true or false)*

And a new clickable message:  When you teleport to the location of a log, there should be a message in chat like "return" or "teleport back" or something, that teleports you to the last location you ran ledger search.

**I don't see why you'd want this, but maybe it should be there just for customization's sake.*

### Describe alternatives you've considered.

I haven't come up with any real alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by WanderingCat27** [comment]
If you want control over the perms of your staff you should prob use a mod like https://www.curseforge.com/minecraft/mc-mods/player-roles. 

this an example config for player roles that would give the role mods access to search functions of ledger w/o the tp function preventing them from tping anywhere even while use /lg s. 
{
  "everyone": {
    "overrides": {
      "commands": {
        "help": "allow"
      }
    }
  },

  "mod": {
    "overrides": {
      "commands": {
        "ban": "allow",
        "kick": "allow",
        "ledger (search|s|page|pg|player)": "allow",
        "gamemode (spectator|survival)": "allow",
        "whitelist (add|remove)": "allow"
      }
    }
  }
}


Though if you specifically want them to be able to tp just locked in place that just seems out of scope of a block logger at least to me.

A return teleport that maybe logged your coordinate once you run /lg s so u could tp anywhere and then do /lg return or smth. Maybe a hash of player name and coordinates. It only needs to exist for the lifetime server and does not need to persist in any capacity so it could just be a simple variable. could be cool ¯\_(ツ)_/¯

**Comment by solonovamax** [comment]
Or better yet: use [Luckperms](https://luckperms.net/)

**Comment by WanderingCat27** [comment]
> Or better yet: use [Luckperms](https://luckperms.net/)

i wanted to use luck perms but I couldnt get it to work on the base permissions like /ban and /whitelist so I chose player roles because i knew it would work
