### ISSUE TITLE
Server Fails to start

### ISSUE THREAD

**Issue by IzzyBizzy45** [QuiltServerTools/Ledger#188]
### Expected behavior

Server Starts

### Observed/actual behavior

Server does not Start

### Steps/models to reproduce

Place the mods needed for Ledger into a server mod folder
Try run the server
Server does not start

### What operating system are you running

Windows

### Minecraft version

1.19.2

### Ledger version

1.2.5

### Logs

https://pastebin.com/rWV8yY4s

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

I've attempted downgrading both Koltin and Fabric API to the lowest versions that are compatible with 1.19.2. No change was experienced

Downgraded Koltin Log (Koltin v1.6.21, Fabric API v0.64.0) - https://pastebin.com/7q0Znukf
Downgraded Fabric API Log (Koltin v1.7.20, Fabric API v0.56.8) -  https://pastebin.com/MhFbmzM1
Both Downgraded Log (Koltin v1.6.21, Fabric API v0.56.8) - https://pastebin.com/ZypL0DWz

Tried loading both just by themselves and they load without any issues - https://pastebin.com/EkFmudKu

**Comment by IzzyBizzy45** [comment]
Was able to run on Another windows machine, experienced the same issue, same downgrade troubleshooting yielded the same results

**Comment by PotatoPresident** [comment]
Try updating fabric loader. Very strange
