### ISSUE TITLE
NBT data is not restored when doing a rollback

### ISSUE THREAD

**Issue by aidan-walden** [QuiltServerTools/Ledger#190]
### Expected behavior

- User breaks chest with items / sign with text / etc
- Server admin rolls back this action
- Chest is now rolled back with its contents intact

### Observed/actual behavior

- User breaks chest with items / sign with text / etc
- Server admin rolls back this action
- Chest is now rolled back, but it is empty

### Steps/models to reproduce

- Place a chest
- Place items inside
- Make a player break the chest
- Roll back the player
- Observe that your items are missing

### What operating system are you running

Windows

### Minecraft version

1.19.2

### Ledger version

1.2.5

### Logs

Not needed

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

It seems like this has been fixed once before
https://github.com/QuiltServerTools/Ledger/issues/33

**Comment by PotatoPresident** [comment]
Looks to be working as intended. Signs rollback correctly. The issue with containers is that the items are removed before the container is actually broken, so they aren't saved in the nbt when the event is called. I have a workaround right now that logs them as separate item removals, but unfortunately there is no player context. You have to rollback the @broke item removals to restore the items at the moment.
![javaw_cKreFaOj5p](https://user-images.githubusercontent.com/51728317/205516591-c5c52e7b-1c81-4881-922f-ecb6b9f1bed3.png)
