### ISSUE TITLE
text shows abnormally (placeholder bug)

### ISSUE THREAD

**Issue by WindLeaf233** [QuiltServerTools/Ledger#194]
### Expected behavior

see the infomations instead of placeholders

### Observed/actual behavior

![image](https://user-images.githubusercontent.com/58383985/210028328-35027ebf-0d8f-4b96-ae2e-cc5db0d914c9.png)

![image](https://user-images.githubusercontent.com/58383985/210028342-89071f76-1256-496a-8c25-f0ca026fb33d.png)

### Steps/models to reproduce

simply run `/ledger status`

### What operating system are you running

Linux

### Minecraft version

1.19.3

### Ledger version

1.2.6

### Logs

https://pastebin.ubuntu.com/p/th3M2T69MF/

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

btw: i use Linux as server, and Windows as my own device system

**Comment by PotatoPresident** [comment]
Update [server translations](https://github.com/NucleoidMC/Server-Translations/releases/tag/v1.4.19%2B1.19.3)
