### ISSUE TITLE
Ledger literally showing no information at all

### ISSUE THREAD

**Issue by spencermacca** [QuiltServerTools/Ledger#206]
### Expected behavior

I ran `/lg search action:block-place object:minecraft:chest source:FatFate` and it should reply with an output similar to CoreProtect where it shows results for this query.

### Observed/actual behavior

When running this command, I am returned with the following:
```
text.ledger.header.search
text.ledger.action_message
text.ledger.action_message
text.ledger.footer.search
```

Upon looking further into this, this weird output happens with all commands ledger related.

### Steps/models to reproduce

1. Install Ledger and its dependencies onto Fabric Server

### What operating system are you running

Linux

### Minecraft version

1.19.4

### Ledger version

1.2.7

### Logs

https://pastebin.com/yZXL9NgN

### Agreements

- [x] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by PotatoPresident** [comment]
Could you try without viaversion/fabric?

**Comment by anaxios** [comment]
I'm having the same issue behind a Velocity proxy running viaversion. The issue goes away if I connect directly to the server without the proxy.

**Comment by anaxios** [comment]
Also works behind the proxy if my client is the same version as the server.

**Comment by meng877** [comment]
I found a temporary workaround to this problem by adding datapack to the server and disabling this packet with `/datapack disable <name>` after each server startup to fix this bug. One drawback is that you have to do it all over again every time you restart the server

My server is running behind the velocity proxy
I can't guarantee that this will solve your problem, I've only tested it on my server 
If you have the same problem, you can try it.
