### ISSUE TITLE
Backport 1.20.x to 1.19.2

### ISSUE THREAD

**Issue by itsdinkd** [QuiltServerTools/Ledger#219]
### Is your feature request related to a problem?

1.19.2 is still widely used, more than 1.19.3/4 and 1.20.1. 

Can we please get a backport for 1.19.2?

### Describe the solution you'd like.

Backport

### Describe alternatives you've considered.

no other alternative

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by suerion** [comment]
The most bigger mods, lile Botania and Create had not released the 1.20.1 version, it take some time. If the newest ledger would be backported, it would be nice.

1.2.5 is for 1.19.2
