### ISSUE TITLE
MySQL logging support.

### ISSUE THREAD

**Issue by KarLYelin** [QuiltServerTools/Ledger#224]
### Is your feature request related to a problem?

I wish ledger could connect to MySQL because SQLite sometimes stores very slowly!

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

I want ledger to connect to MySQL.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by arnokeesman** [comment]
see [ledger-databases](https://github.com/QuiltServerTools/Ledger-Databases)
