### ISSUE TITLE
crash on server startup

### ISSUE THREAD

**Issue by Dan4oby** [QuiltServerTools/Ledger#229]
### Expected behavior

...

### Observed/actual behavior

...

### Steps/models to reproduce

1. Launch server only with fabric api and kotlin fabric.
2. Get crash

### What operating system are you running

Windows

### Minecraft version

1.20.2

### Ledger version

1.2.9

### Logs

https://pastebin.com/bsMhJALs

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by arnokeesman** [comment]
Known issue on the discord, add [mixinextras-fabric-0.2.0-beta.8.jar](https://github.com/LlamaLad7/MixinExtras/releases/download/0.2.0-beta.8/mixinextras-fabric-0.2.0-beta.8.jar) to your mods folder (from [this](https://github.com/LlamaLad7/MixinExtras/releases/tag/0.2.0-beta.8) release)
