### ISSUE TITLE
Add the location of the [ledger.sqlite] file in the configuration, which can be placed in another directory

### ISSUE THREAD

**Issue by syjmc** [QuiltServerTools/Ledger#234]
### Is your feature request related to a problem?

Comment placer [ledger.sqlite] en dehors du dossier [world], ce qui donnera une très grande et longue sauvegarde du fichier [world].

### Describe the solution you'd like.

Add the location of the [ledger.sqlite] file in the configuration, which can be placed in another directory
English is not my native language so I can't find the settings, if the problem has been solved then can you tell me the answer, sorry!

### Describe alternatives you've considered.

Add the location of the [ledger.sqlite] file in the configuration, which can be placed in another directory

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

### Other

![image](https://github.com/QuiltServerTools/Ledger/assets/147303286/09c7e3f9-b198-47d4-8b63-014f43076988)

**Comment by McMelonTV** [comment]
agreed, would be great if this was added
