### ISSUE TITLE
1.20.4 version of the mod pls

### ISSUE THREAD

**Issue by NotFlow69** [QuiltServerTools/Ledger#237]
### Is your feature request related to a problem?

release the 1.20.4 version of the mod. because its one of the best logging mods ever

### Describe the solution you'd like.

release the 1.20.4 version of the modd

### Describe alternatives you've considered.

release the 1.20.4 version of the modd

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by RandomGgames** [comment]
Seems like it's in the works if you look at the recent commits.

**Comment by NotFlow69** [comment]
oh alright!
