### ISSUE TITLE
Server doesn't starts

### ISSUE THREAD

**Issue by Timtaran** [QuiltServerTools/Ledger#238]
### Expected behavior

server starts

### Observed/actual behavior

server don't starts

### Steps/models to reproduce

1. Install [Prominence II RPG](https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg) modpack
2. Add Ledger mod.

### What operating system are you running

Windows

### Minecraft version

1.20.1

### Ledger version

1.2.8

### Logs

https://hastebin.com/share/ukajifunoy.rust

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Yizhouuu** [comment]
same issue with same modpack

**Comment by Yizhouuu** [comment]
> same issue with same modpack

ill try update modpack later as it seems to be issue with fabric loader

**Comment by PotatoPresident** [comment]
Logs have expired

**Comment by Mavodeli** [comment]
The issue with that specific modpack lies with the mod `Let's do vinery`.

Version `1.4.6` had conflicting mixins with ledger (and very many other mods) that were fixed on the same day the version was released. 
On Modrinth `1.4.6` was replaced with the patched version, while on Curseforge the patched version is found under `1.4.6b`: [https://www.curseforge.com/minecraft/mc-mods/vinery/files/4829431](https://www.curseforge.com/minecraft/mc-mods/vinery/files/4829431)

Unfortunately the modpack hasn't updated the mod so if you are using the curseforge version of the modpack you need to patch the server (and any clients that want to use ledgers client side mod) manually.
