### ISSUE TITLE
The permissions don't work

### ISSUE THREAD

**Issue by Blayung** [QuiltServerTools/Ledger#256]
### Expected behavior

After setting `ledger.inspect` (README.md) or `ledger.commands.inspect` (luckperms suggestion) to true in the default group with luck perms, I wanted everybody on my server to be able to inspect the logs.

### Observed/actual behavior

Nothing has changed.

### Steps/models to reproduce

Described in `Expected behavior`

### What operating system are you running

Linux

### Minecraft version

1.20.1

### Ledger version

1.2.8

### Logs

https://paste.ee/p/R92PI

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by arnokeesman** [comment]
you're missing `ledger.commands.root`

**Comment by Blayung** [comment]
Yes, indeed! I have to enable both `ledger.commands.root` and `ledger.commands.inspect` (`ledger.inspect` doesn't work). Thanks! Is this documented somewhere?

**Comment by arnokeesman** [comment]
yup, on the wiki, you can find it on Modrinth -> Wiki, or Modrinth -> Descripttion#docs -> link or GitHub -> wiki -> link

**Comment by Blayung** [comment]
That's quite hard to find, I think somebody should edit the README.md.
