### ISSUE TITLE
server crash in version 1.3.3 using latest fabric server 1.21

### ISSUE THREAD

**Issue by Saxostevesaxo** [QuiltServerTools/Ledger#274]
### Expected behavior

installed new 1.21 version to my server and expect to see server start with no errors

### Observed/actual behavior

Server crashes
log linked below

### Steps/models to reproduce

install on a 1.21 server
start server
server crashes with above errors

### What operating system are you running

Windows

### Minecraft version

1.21

### Ledger version

1.3.3

### Logs

https://pastebin.com/xw1P5Ftw

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by DrexHD** [comment]
Thanks for reporting, 1.3.3 is for 1.20.6 only and has been incorrectly marked as 1.21! I have now fixed this on modrinth. An official 1.21 ledger build should be released soon!

**Comment by Saxostevesaxo** [comment]
ok great thankyou!
