### ISSUE TITLE
Writing in a book and quill without signing will cause all players to be kicked when you press 'done' in the interface

### ISSUE THREAD

**Issue by jack-bkr** [QuiltServerTools/Ledger#3]
This will also kick all players connected to the server whenever the player with the book and quill joins.
I've included a video showing how to reproduce this and the server log from this video as well.

https://streamable.com/eoob09
[latest.log](https://github.com/QuiltServerTools/Ledger/files/6603899/latest.log)

**Comment by caesarakalaeii** [comment]
Your log states a malformed Json Exception.
Could you provide your config Json?

**Comment by jack-bkr** [comment]
I didn't change anything in the config file, its a fresh server with no config files being changed

**Comment by yitzy299** [comment]
https://github.com/arthurbambou/Server-Translations/pull/13

**Comment by PotatoPresident** [comment]
Fixed
