### ISSUE TITLE
Ledger sometimes does not log some actions and spam errors to the console.

### ISSUE THREAD

**Issue by FlamingCherry** [QuiltServerTools/Ledger#51]
**Describe the bug**
Hello. First of all, I want to say thank you for developing this wonderful mod, without which a quiet game on vanilla servers is impossible. But unfortunately, very, very often various errors occur with this mod. For example, for some unknown reason, it very often does not record even the most common actions of players, such as placing and breaking blocks, and after a few seconds it starts logging again. You can see an example in the screenshot. I made a small install from TNT and blew it up, then rolled it back with Ledger. As you can see, only a small part in the middle of the crater has rolled back. The rest, what did not roll back, is not even logged.

**To Reproduce**
I don’t know how exactly to repeat this, these problems occur randomly. Just try to do some action, break and destroy blocks, blow up TNT, etc., and then try looking at the logs with the Ledger.

**Expected behavior**
Well, I don't even know, probably normal logging of all actions. ¯\_(ツ)_/¯

**Screenshots**
https://i.ibb.co/0YZK5Yc/2021-06-28-00-06-34.png

**Device Info(please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.17
 - Version: 1.0.1

**Log**
https://hastebin.com/ohiqalicuf.yaml

**Additional context**
In my server log you will see many different errors, they all seem to be due to Ledger, I still do not understand exactly when they appear, it seems that randomly. Without it, these errors do not arise. Hopefully you can fix that as this mod is a must have for small vanilla servers. 🙏

**Comment by yitzy299** [comment]
Duplicates #48

**Comment by PotatoPresident** [comment]
Updated to the [latest build from github actions](https://github.com/QuiltServerTools/Ledger/actions/runs/977902042) should resolve all of the errors. As for it only rolling back part of the explosion, it can take a decent amount of time to fully log explosions. I would wait until it says the database is no longer busy in `/ledger status`. If you continue of have issues, let us know.
