### ISSUE TITLE
Not all result given that are available

### ISSUE THREAD

**Issue by vacla** [QuiltServerTools/Ledger#55]
**Describe the bug**
It seems that it only shows the first few results

**To Reproduce**
/ledger search action:block-break time:100w range:50
/ledger search time:100w range:50
/ledger search action:block-break range:50
/ledger search action:block-break time:100w
/ledger search action:block-break time:100w range:5

**Expected behavior**
Give all results back not the first ones only

**Screenshots**
https://streamable.com/gcyblb

**Device Info(please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.17.0
 - Version 1.0.0
 - Watson watson-fabric-1.17.0-1.11.0.20210703.224053

**Log**
https://gist.github.com/vacla/93aca1c4ab3641448e055663b0bb4b8e

**Additional context**

**Comment by PotatoPresident** [comment]
This is only when using the client mod networking api

**Comment by vacla** [comment]
Closing since heard nothing back anymore after fix
