### ISSUE TITLE
No results shown for queries of any kind

### ISSUE THREAD

**Issue by yitzy299** [QuiltServerTools/Ledger#57]
When running any form of query (Search, inspect, rollback, preview) there are no results returned by the database. All actions remain logged, and no errors are in the server logs

**To Reproduce**
1. Run a command querying the database

**Screenshots**
![image](https://user-images.githubusercontent.com/66269211/125243788-751b2200-e2e6-11eb-8e6d-7bf4ba4a631c.png)

**Device Info:**
 - OS: *
 - Minecraft Version: 1.17
 - Version: 1.0.2

**Additional context**

Is caused by either 458802d or 2ae0ec2

**Comment by PotatoPresident** [comment]
Can't reproduce
