### ISSUE TITLE
Support more database types

### ISSUE THREAD

**Issue by PotatoPresident** [QuiltServerTools/Ledger#6]
- [x] MySQL

- [x] H2

- [ ] Postgres

**Comment by JulienTant** [comment]
Others could include Postgres, I think with h2, MySQL and postgres you covered most db that people use 👍

**Comment by yitzy299** [comment]
https://github.com/QuiltServerTools/Ledger-Databases/commit/a45768283815faf61cf60de861f0daf5fe8e6487
