### ISSUE TITLE
[BUG] Not logging placement of fire

### ISSUE THREAD

**Issue by RandomGgames** [QuiltServerTools/Ledger#64]
**Describe the bug**
If a player uses flint and steel to place fire than break it, using /lg i only shows that the fire is placed, not who placed it or how.

**To Reproduce**
1. Place fire using flint and steel
2. Break the fire
3. Inspect the block

**Expected behavior**
The logs show that someone placed the fire and destroied it, not just destroied it.

**Device Info(please complete the following information):**
 - OS: Windows
 - Minecraft Version 1.17.1 (mods: environmental creepers, fabric api, carpet, tree chopper, lithium, minitweaks, servux, voicechat, xaero's minimap)
 - Version 1.0.2

**Comment by yitzy299** [comment]
Adding an event trigger on the flint and steel use method should suffice
