### ISSUE TITLE
Command doesn't work on MC 1.17.1

### ISSUE THREAD

**Issue by MAX-XiaoKui** [QuiltServerTools/Ledger#65]
### Expected behavior

I can use the `/ledger` command normally.

### Observed/actual behavior

Command `/ledger` and `/lg` doesn't work.

### Steps/models to reproduce

0. OS: Debian 10.10, also tried Windows 10
1. Install **AdoptOpenJDK-16-jre** (*Both Hotspot and OpenJ9 are tried*)
2. Install **fabric server** (*MC* `1.17.1`, *fabric loader* `0.11.6`)
3. Install **mods** (*fabric api* `0.37.0`, *fabric language kotlin* `1.6.3+kotlin.1.5.21`(also tried `1.6.2+kotlin.1.5.20`), *ledger* `1.0.2`)
4. **Start the server**
5. Enter command `ledger` (Also tried using a client)

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.0.2

### Logs

https://hastebin.com/egegopesek.sql

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Database are updated normally.

**Comment by vacla** [comment]
I believe this is the same issue as #57

**Comment by MAX-XiaoKui** [comment]
No, when I type `/ledger i`, it **doesn't** even output `Inspect mode: Enabled`
![image](https://user-images.githubusercontent.com/53287753/126784302-71608fce-e04f-4f87-ab49-865e6832655a.png)

**Comment by yitzy299** [comment]
You don’t have the root permission node or the fallback level

**Comment by PotatoPresident** [comment]
You need to be a level 3 OP, it give yourself the required nodes with a permission manager like luckperms.
https://quiltservertools.github.io/Ledger/1.0.1/commands/root/

**Comment by MAX-XiaoKui** [comment]
OK, thx.
