### ISSUE TITLE
Extreme lag in searching very large database files

### ISSUE THREAD

**Issue by Captain-S0L0** [QuiltServerTools/Ledger#70]
### Expected behavior

A quick response from the database, perhaps only a few seconds.

### Observed/actual behavior

Often waiting over a minute for a search result to return.

### Steps/models to reproduce

1. Collect a very large database (my server's database file is currently 13GB)
2. Run any ledger command that would return a page of logged actions (e.x. /lg s radius:5)

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.0.2

### Logs

https://pastebin.com/KhphPhEF

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

This isn't _exactly_ a bug, but a very annoying result of large database files that makes searching for wrongdoers difficult when time is of the essence. Possible solutions range from more optimized search methods to simply creating separate database files for different periods of time, such as one for every day or week, or when it reaches a preconfigured size such as 1GB.

If you would like my database to test with so you don't have to generate one yourself, let me know.

**Comment by PotatoPresident** [comment]
The database file would be appreciated, can we discuss this further on discord?
https://discord.gg/cSWma7DupQ
