### ISSUE TITLE
Allow searches with NOT as an argument 

### ISSUE THREAD

**Issue by RandomGgames** [QuiltServerTools/Ledger#75]
### Is your feature request related to a problem?

It would be nice if at someone's base, to look for any action that isn't the owner's. For example, at RandomGgames' base, I can't search for actions that are by everyone except RandomGgames.

### Describe the solution you'd like.

Add a feature for :!{Username} in the search conditions or :NOT:{Username} or something like that.

### Describe alternatives you've considered.

The only real way to do this is to scroll through the search, ignoring everything except the username you want to ignore. Not sure if there's an easier way currently.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by Binero** [comment]
Perhaps just use ! as a syntax? Something like one of these:

- `!source:Binero`
- `source:!Binero`
