### ISSUE TITLE
Conflict with Gunpowder Mod

### ISSUE THREAD

**Issue by yhr0x43** [QuiltServerTools/Ledger#77]
### Expected behavior

Ledger logs actions and being able to query them.

### Observed/actual behavior

If installed alongside Gunpowder, Ledger wouldn't record any action, neither be able to query them. Each action causes some error message.

### Steps/models to reproduce

1. On a fabric server, install ledger, [gunpowder-base](https://www.curseforge.com/minecraft/mc-mods/gunpowder-mc), 2. (also fabric API and fabric language Kotlin as they are needed by gunpowder)
3. Launch the server, the server will start and run normally except for some error message.
4. Use Ledger and notice something is wrong

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.0.2

### Logs

https://pastebin.com/m9qEWqAs

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

Copied from Gunpowder Curseforge page to serve as a definition of this term.
> Gunpowder aims to provide an all-in-one API for your server modding needs.

**Comment by PotatoPresident** [comment]
Gunpowder is incompatible with Ledger because both mods use Exposed and Gunpowder does not shade Exposed.
Most things gunpowder does have better alternatives.

**Comment by PotatoPresident** [comment]
Duplicate of #13
