### ISSUE TITLE
Conflict with Better Hoppers

### ISSUE THREAD

**Issue by elhertz** [QuiltServerTools/Ledger#85]
### Expected behavior

Be able to open any kind of hopper when using ledger and [BetterHoppers](https://www.curseforge.com/minecraft/mc-mods/hopper)

### Observed/actual behavior

I can't open any kind of hopper and when I try to do so an error is thrown in the console.

### Steps/models to reproduce

Use:
  [✔️] fabric-api-0.40.1+1.17
  [✔️] fabric-language-kotlin-1.6.4+kotlin.1.5.30
  [✔️] flytre-lib-1.3.7
  [✔️] hplus-3.0.1
  [✔️] ledger-1.0.2

Try to open any hopper container.

### What operating system are you running

Windows

### Minecraft version

1.17.1

### Ledger version

1.0.2

### Logs

Server log https://paste.lucko.me/7ndXtWGxa7

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by vacla** [comment]
@elhertz this is not because of ledger, it is caused by flytre_lib see 
`java.lang.NullPointerException: Cannot invoke "net.flytre.flytre_lib.api.storage.upgrade.UpgradeInventory.getUpgrade(int)`

**Comment by yitzy299** [comment]
Flytre lib has not assigned a value internally to the slot by the time. Ledger requires this to be able to log container transactions. Please speak to the flytre lib devs to fix this

**Comment by elhertz** [comment]
Thank you.
